### ISSUE TITLE
[FE] Poprawki w widoku zamówień

### ISSUE THREAD

**Issue by ochnios** [Kacprucha/KateringApp#34]
- wyświetlanie wartości zamówienia
- wyświetlanie posiłków z jakich składa się zamówienie
- ~~na liście zawsze wyświetlany jest status COMPLETED zamiast rzeczywistego aktualnego statusu zamówienia~~ ogarnięte w ramach [Feature/split microservices functionality #39](https://github.com/Kacprucha/KateringApp/pull/39)
- w tabeli powinien wyświetlać się username klienta od którego pochodzi zamówienie

**Comment by bilskik** [comment]
Będzie poprawione jak BE doda endpoint który udostępni ordery z posiłkami - napisałem już do ziomka żeby to ogarnął
