### ISSUE TITLE
[BE] łatanie dziur - posiłki

### ISSUE THREAD

**Issue by ochnios** [Kacprucha/KateringApp#41]
- należy dodać powiązanie posiłku z firmą kateringową do której należy
- firma cateringowa powinna mieć dostęp do podglądu i wszelkich modyfikacji tylko do należących do niej posiłków

**Comment by MaciekK2001** [comment]
jeśli chodzi o pierwsze to każdy posiłek ma przypisaną firmę kateringową, także nie do końca rozumiem co jest do poprawy, chodzi o to żeby przy pobieranym DTO posiłku dodać firmę kateringową do której posiłek należy?

**Comment by ochnios** [comment]
tak, id + nazwa firmy żeby potencjalnie wyświetlić na froncie
