### ISSUE TITLE
[FE] Formularz składania zamówienia na podstawie zawartości koszyka

### ISSUE THREAD

**Issue by Kacprucha** [Kacprucha/KateringApp#59]
- Uzupełnienie danych – imię i nazwisko, dane kontaktowe, adres, sposób płatności, możliwe dane powinny być pobierane z danych użytkownika pola powinny zostać jednak edytowalne gdyby użytkownik chciał zmienić np adres

**Comment by PWDamian** [comment]
czeka na https://github.com/Kacprucha/KateringApp/pull/53
