### ISSUE TITLE
[FE] Wyświetlanie/dodanie brakujących szczegółów do zamówień

### ISSUE THREAD

**Issue by Kacprucha** [Kacprucha/KateringApp#60]
- Imię, nazwisko, dane kontaktowe, adres, data zamówienia, data realizacji

**Comment by szymon-skiba** [comment]
Po stronie firmy w widoku myOrders?

**Comment by Kacprucha** [comment]
Myśle że po obu stronach jak klijent podejrzy swoje zamówienia to też warto żeby mógł zobaczyć te dane
