### ISSUE TITLE
[BE] Endpoint dla wykresu zysków

### ISSUE THREAD

**Issue by Kacprucha** [Kacprucha/KateringApp#68]
- Tak aby można było filtrować wg opisu wykresu na froncie (do atrybutów zamówienia trzeba dodać datę) 
- Tylko opłacone zamówienia powinny być brane pod uwagę

**Comment by MaciekK2001** [comment]
chodzi o datę utworzenia, czy datę na kiedy zamówienie ma być dostarczone?

**Comment by Kacprucha** [comment]
Tbh to powinna być data zmienia statusu zamówienia na opłacone bo to ma być wykres zysków
