### ISSUE TITLE
[BE] Update danych klijenta

### ISSUE THREAD

**Issue by Kacprucha** [Kacprucha/KateringApp#74]
- Do encji klienta należy dodać imię, nazwisko, nr telefonu, adres jeżeli jeszcze nie istnieją
- Dodać odpowiednie pola w bazie danych aby była możliwość zapisu
- Wystawienie endpointów aby była możliwość updatu danych klienta

**Comment by PWDamian** [comment]
Dodam jeszcze, żeby uwzględnić możliwość nie tylko zapisu, ale też pobrania tych danych oraz, żeby możliwie priorytetowo zająć się tym taskiem, bo dużo innych od niego zależy

**Comment by arkadiuszc2** [comment]
Ok, zajmę się tym taskiem w ten weekend
